language: rust
cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.cache/sccache"
before_cache:
- rm -rf "$HOME/.cargo/registry"
env:
  global:
  - CRATE_NAME=mdbook
before_install:
- export SCCACHE_VER=0.2.8 RUSTC_WRAPPER=sccache
- case "$TRAVIS_OS_NAME" in linux ) cd /tmp && travis_retry curl -sSL "https://github.com/mozilla/sccache/releases/download/${SCCACHE_VER}/sccache-${SCCACHE_VER}-x86_64-unknown-linux-musl.tar.gz"
  | tar xzf - && sudo mv "sccache-${SCCACHE_VER}-x86_64-unknown-linux-musl/sccache"
  /usr/local/bin/sccache; ;; osx ) cd "${TMPDIR}" && travis_retry curl -sSL "https://github.com/mozilla/sccache/releases/download/${SCCACHE_VER}/sccache-${SCCACHE_VER}-x86_64-apple-darwin.tar.gz"
  | tar xzf - && sudo mv "sccache-${SCCACHE_VER}-x86_64-apple-darwin/sccache" /usr/local/bin/sccache;
  ;; * ) unset RUSTC_WRAPPER;; esac
- cd "$TRAVIS_BUILD_DIR"
script:
- cargo build
deploy:
  provider: releases
  api_key:
    secure: ey58Fz43+geb89PeF8Mbap8HAdsetuwR8KgCWNSM7Pgfe5yCkoLVK2xJBgSeMdvtjUwGO/5viZx5kuFIJ7UFewSEVvz/Lraxe7WNcMDXSRGZTeVly1tLnvZiEPDutlq1UeCz9HWo287SoxxrKop9fZlhoar63IgOxfrYTe93XcHa2BJjKVlke5AP1Mw733+HJcFHbb9aYQYDobHnJpD7SpyseQ2UaOujqpn/P67Ahk3cmbO4Bxftk10PT9PNIrRyd+Sez4+NbeNNXFjv4cdKrngMvXe+ZC/3cPStzV4TiGplKndVqCVgds3QqviyGa28RiBdxIzqdQ9GpnektvsUWjcoZXYQS484OTY9mSYBj5LMOJXgdcFwqTJZTjJpzrcnSFz2K/DDf1sBThvUmhN/S/8/4kd+iibP6Hh60bK0dZhyy4U4M8TNv1yaL2GKSkCTKrMYnKpOZV6P0BDKe507fyVXnM5UTaKCnXMhhS4Mb6pFFmpapM+LnH6MHi2/Hbfd0uDUTrZ888X9iTgPe4jDqpARjq+zgtuzz6YYVfVWuPP/kacKqAW7f2krIMegQ8cuiACq9hqCPVIkm7WHs/W9I32nlM+PAMabSwlKmPSXuvQ+D/J4nLxEEpUSmhdklnfLq7e4tlDJZ0yXN0DNUE6VEltG5ecZfdJNUPqmAC2L1W4=
  file: target/debug/mdbook
  skip_cleanup: true
  draft: true
